# Generated by Django 5.1.4 on 2026-06-30 11:03

from django.db import migrations

def create_default_scripts(apps, schema_editor):
    TrainingScript = apps.get_model('training', 'TrainingScript')
    
    script_content = """(You are doing an investigation) Hello, (name)? This is (your first name) BEAR WITH ME FOR JUST A MINUTE, I’M TRYING TO FIND OUT WHAT HAPPENED HERE. You had ‘contacted’ us about the death and illness protection on the mortgage loan… I’m the (Regional Manager (OR) Senior Field Underwriter), did anyone get back with you on this, that you that you know of? (Get the story and react accordingly. Build a connection and simply have a conversation about whether or not they were handled properly. IF NOT…-)
With everything going on we’re a bit backed up on these requests, I’ll go ahead and step in and get your options to you ... I just quickly need to verify the information you gave us... (Verify date of birth, smoking status, and confirm loan amount, & is it a 30-year term? What is their height/weight? What is their monthly mtg. payment? Do they have any life insurance, critical illness plans, or retirement funds to cover the loan? Collect all the information you can, in order to prepare properly. Ask the same questions about their spouse if they have one.)
Ok, now, I just need to ask you some quick qualifying questions so I know exactly which options you’re eligible for… have you dealt with any health conditions over your lifetime? Do you take any medications? Have you been diagnosed with or filled meds for Covid in the last 90 days?  What about your spouse? Ok, no problem. (It doesn’t matter either way, we specialize in protecting those with serious health conditions.) (DIG DEEP AND COLLECT EVERY DETAIL POSSIBLE!)
Now, I’m assuming if something happens to you, you just wanted to make sure your family doesn’t lose the home, is that right? Tell me more about that… Can you tell me who the primary income earner is? (Dig deep on this topic to build emotion. Ask more questions if needed in order to find out their “WHY”. We are looking to see if they have a problem for us to solve or not.)
Okay, I’ll tell you quickly how it works. A few years back, they would have you do a full physical exam. You don’t have to do that any longer, but they just require me to visually verify that you are not in a hospital bed or wheelchair, and at that time we can go the options you are eligible for. It takes about 15-20 minutes (Keep going) If it doesn’t make sense for you that’s fine, we’ll just close out your file. If it DOES, we still have to get you approved, so I’ll collect some information, and send it through underwriting. It takes a few weeks to hear back. (Keep going and assume the appointment.) 
They have me out near ___________ (their street name), on ___________ and ___________(days), what is a 15 minute time that works for you (both of you) and I’ll see if I can squeeze you in… (Set appt.) (Verify their address.) (Make sure both husband and wife will be there.)
If you don’t mind, would you grab a pen and jot down the time and day for me? With everything going on, I’m running a pretty tight schedule, if you could do your best to be there, I would GREATLY appreciate it. Oh, and by the way, don’t do ANYTHING special for me, don’t clean or dress up, I’m going to be in and out, okay? Is there any reason why you WOULDN’T be able to make it at that time? Great, see you on ____________. (Repeat date, time, and address) (TIE IT DOWN!)"""

    system_prompt = """You are a homeowner who recently inquired about mortgage protection insurance.
When the agent calls, you are mildly confused at first, but willing to talk.
The agent needs to extract your information (age, health conditions, spouse details, mortgage amount) and book an appointment with you.
If the agent asks probing questions, answer them naturally as the homeowner."""

    TrainingScript.objects.create(
        title="JD Rogers Group Face-to-Face MP Phone Script",
        category="Mortgage Protection",
        difficulty="medium",
        content=script_content,
        system_prompt=system_prompt,
        is_default=True
    )

def remove_default_scripts(apps, schema_editor):
    TrainingScript = apps.get_model('training', 'TrainingScript')
    TrainingScript.objects.filter(title="JD Rogers Group Face-to-Face MP Phone Script").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_scripts, remove_default_scripts),
    ]
